name: "Lint"

on:
  push:
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Rust"
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - name: "Lint code"
        uses: super-linter/super-linter@v6.7.0
        with:
          cargo: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
